### ISSUE TITLE
Encoding error with non-text data

### ISSUE THREAD

**Issue by SeanDS** [duncanmmacleod/ligo.org#4]
When I try to download a PDF from the DCC, I get the following error (both Python 2 and 3):

```
>>> from ligo.org import request
>>> request("https://dcc.ligo.org/DocDB/0077/T1100616/002/T1100616-v2.pdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ligo/org/ecp.py", line 330, in request
    return out.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc4 in position 10: invalid continuation byte
```

Seems like `request` should not assume UTF-8 encoding, or at least it should try to identify the encoding and handle it appropriately.

**Comment by duncanmmacleod** [comment]
@SeanDS, I'm tempted to say that the request should not presume anything about the encoding, and just return the `bytes` object as returned from the HTTP request, and leave the user to handle everything else the way they want. I will open a PR that implements this

**Comment by SeanDS** [comment]
I suppose another approach would be to have `request` return raw data, but also provide `request_unicode` or `request_str` to both fetch and decode the data.
